### ISSUE TITLE
Using the appropriate Memgraph Docker image

### ISSUE THREAD

**Issue by gitbuda** [memgraph/example-streaming-app#21]
If `memgraph/memgraph:latest` already exists on the machine, `memgraph/run.sh memgraph` won't actually use the latest Memgraph image.

Probably the best would be to hardcode Memgraph version where everything is working as expected, e.g. v1.6.0.

**Comment by MasterMedo** [comment]
Ideally we would check if `latest` version is at least 1.6.0 and go with that, if it isn't we would do a `docker pull`. I'll research if that's possible.

**Comment by MasterMedo** [comment]
It seems the best practice is to add the `--pull` option to the `docker run` command.
