### ISSUE TITLE
Updating neighbors doesn't work

### ISSUE THREAD

**Issue by gitbuda** [memgraph/example-streaming-app#22]
**Bug Description**
When running `kafka/producer/stream_producer.py`, the `neighbors` property on each node always stays 0. Sometimes the node doesn't even contain the property.

**To Reproduce**
Just run property initialized Memgraph + any backend + `stream_producer.py`.

**Expected behavior**
As new nodes/edges come in, the `neighbors` should be incrementally updated.

**Desktop:**
OS: Ubuntu 20.04

**Comment by MasterMedo** [comment]
Cannot reproduce. It works nicely for me with the python backend, and I used all the scripts we provide (run.sh for memgraph and kafka). Only the first node that is entered throws the "neighbors aren't set" error.

**Comment by MasterMedo** [comment]
I managed to reproduce on a clean pull. Seems like I had fixed the issue locally but haven't pushed. The issue is that new nodes aren't updated, no property is being changed, I'll add a fix soon.
